name: Metrics

on:
  schedule: [{cron: "0 */6 * * 1"}]
  workflow_dispatch:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    environment: production
    steps:

      - name: Metrics - Steam
        uses: lowlighter/metrics@latest
        with:
  
          # Auth & Commit Settings
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "chore: update metrics"
          base: ""
          filename: metrics.plugin_steam.svg
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "76561199601847108"
          plugin_steam_sections: player, most-played
          plugin_steam_playtime_threshold: 100000
          plugin_steam_games_limit: 1
          plugin_steam_achievements_limit: 2
          

      - name: Metrics - Languages
        uses: lowlighter/metrics@latest
        with:
          # Auth & Commit Settings
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "chore: update metrics"
          base: ""
          filename: metrics.plugin_languages.svg
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4

      - name: Metrics - Isocalendar
        uses: lowlighter/metrics@latest
        with:
              
          # Auth & Commit Settings
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "chore: update metrics"
          base: ""
          filename: metrics.plugin_isocalendar.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: quarter

      - name: Metrics - Stars
        uses: lowlighter/metrics@latest
        with:
          # Auth & Commit Settings
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "chore: update metrics"
          base: ""
          filename: metrics.plugin_stars.svg
          plugin_stars: yes
          plugin_stars_limit: 3

      - name: Metrics - Repositories
        uses: lowlighter/metrics@latest
        with:
          # Auth & Commit Settings
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "chore: update metrics"
          base: ""
          filename: metrics.plugin_repositories.svg
          plugin_repositories: yes
          plugin_repositories_featured: Stefodan21/Forex-trading-bot, Stefodan21/Order_fulfillment_Project, Stefodan21/Stefodan21.github.io

      - name: Metrics - LeetCode
        uses: lowlighter/metrics@latest
        with:
          # Auth & Commit Settings
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "chore: update metrics"
          base: ""
          filename: metrics.plugin_leetcode.svg
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_limit_skills: default

      - name: Metrics - Activity
        uses: lowlighter/metrics@latest
        with:
          # Auth & Commit Settings
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "chore: update metrics"
          base: ""
          filename: metrics.plugin_activity.svg
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 7
          plugin_activity_filter: push, pr, fork, ref/create, ref/delete

      - name: Metrics - WakaTime
        uses: lowlighter/metrics@latest
        with:
          # Auth & Commit Settings
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "chore: update metrics"
          base: ""
          filename: metrics.plugin_wakatime.svg
          plugin_wakatime: yes
          plugin_wakatime_username: Stefodan21
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
