name: Metrics

on:
  schedule: [{cron: "0 0 * * 1,5"}]  # Runs Runs at 00:00, only on Monday and Friday.
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Auth & Commit Settings
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main
          committer_message: "chore: update metrics"

          # General Config
          config_display: columns
          config_columns: 3
          config_timezone: US/Eastern
          template: classic
          user: Stefodan21
          filename: metrics.repository.svg

          # Plugins
          plugin_lines: yes
          

          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "76561199601847108"
          plugin_steam_sections: recently-played
          plugin_steam_playtime_threshold: 100000
          plugin_steam_achievements_limit: 3
          plugin_steam_recent_games_limit: 1

          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_stars: yes
          plugin_stars_limit: 3

          plugin_repositories: yes
          plugin_repositories_featured: Stefodan21/Forex-trading-bot, Stefodan21/Order_fulfillment_Project

          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_limit_skills: default

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 7
          plugin_activity_filter: push, pr, fork, ref/create, ref/delete

          plugin_wakatime: yes
          plugin_wakatime_username: Stefodan21 
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

          # Display order
          config_order: base.header, isocalendar, languages, lines, activity, wakatime, leetcode, stars, repositories, steam
